### ISSUE TITLE
Composer install error

### ISSUE THREAD

**Issue by nikolas-haug** [brainstormforce/astra-sites#364]
Hello,

I'm having a few issues installing astra-sites plugin via composer. After adding relevant lines to my composer.json file and running update, I see these errors:

_Problem 1
    - Root composer.json requires brainstormforce/astra-sites dev-master -> satisfiable by brainstormforce/astra-sites[dev-master].
    - brainstormforce/astra-sites dev-master requires brainstormforce/gutenberg-templates ^1 -> could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Root composer.json requires brainstormforce/ultimate-addons-for-gutenberg dev-master -> satisfiable by brainstormforce/ultimate-addons-for-gutenberg[dev-master].
    - brainstormforce/ultimate-addons-for-gutenberg dev-master requires brainstormforce/gutenberg-templates ^1 -> could not be found in any version, there may be a typo in the package name._

I see in your composer.json file that you require the missing dependency: 

_"require": {
          "brainstormforce/astra-notices": "^1.1",
           "brainstormforce/gutenberg-templates": "^1"
 },_

When attempting to locate this repo:

_"url": "git@github.com:brainstormforce/gutenberg-templates.git_

it doesn't appear to exist. Is it possible there is an error in your composer.json file? Or is the _gutenberg-templates_ repo private? 

Thanks in advance!

**Comment by Nikschavan** [comment]
The repo `brainstormforce/gutenberg-templates` is indeed a private repo, We will get this open sourced very soon.

Until then I will recommend to use [wpackagist.org](https://wpackagist.org/search?q=astra-sites&type=any&search= )
